language: scala

jdk:
  - oraclejdk8

scala:
  - 2.12.4

sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

script:
  - sbt clean coverage ++$TRAVIS_SCALA_VERSION test coverageReport

after_success:
  - "[[ $TRAVIS_BRANCH == \"master\" ]] && { sbt +publish; };"
  - bash <(curl -s https://codecov.io/bash)
